version: '3'
services:
  mysql:
    restart: always
    container_name: elephantwhale_mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile${MYSQL_VERSION}
    ports:
      - 33061:3306
    volumes:
      - ${HOST_PATH_TO_APP}/data/mysql${MYSQL_VERSION}/:/app/
      - ${HOST_PATH_DB_SCRIPT}/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  adminer:
    image: adminer:latest
    ports:
      - 8091:8080
    links:
      - mysql