version: '3'
services:
  cli:
    build:
      context: ./cli
      dockerfile: Dockerfile${PHP_VERSION}
    image: elephant-whale-php/cli:${PHP_IMAGE_TAG}
    links:
      - mysql
      - redis
      - beanstalkd
  composer:
    build:
      context: ./composer
      dockerfile: Dockerfile${PHP_VERSION}
      args:
        - COMPOSER_VERSION=${COMPOSER_VERSION}
    depends_on:
      - cli
    image: elephant-whale-php/composer:${PHP_IMAGE_TAG}
  fpm:
    build:
      context: ./fpm
      dockerfile: Dockerfile${PHP_VERSION}
    expose:
      - 9000
    volumes:
      - ${HOST_PATH_TO_APP}/:/app/
    depends_on:
      - cli
    links:
      - mysql
      - redis
      - beanstalkd
  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
    links:
      - fpm
  mysql:
    restart: always
    build:
      context: ./mysql
    ports:
      - 33061:3306
    volumes:
      - ${HOST_PATH_TO_APP}/data/mysql/:/app/
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  redis:
    image: redis:alpine
    volumes:
      - ${HOST_PATH_TO_APP}/data/redis/:/data
  beanstalkd:
    build:
      context: ./beanstalkd
    volumes:
      - ${HOST_PATH_TO_APP}/data/beanstalkd/:/data
  node:
    image: node:6-alpine
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ${HOST_PATH_TO_APP}/:/usr/src/app
    expose:
      - 8080
