version: '3'
services:
  cli:
    build:
      context: ./cli
    image: phpenv/cli:latest
  composer:
    build:
      context: ./composer
      args:
        - COMPOSER_VERSION=${COMPOSER_VERSION}
    depends_on:
      - cli
    image: phpenv/composer:latest
  fpm:
    build:
      context: ./fpm
    expose:
      - 9000
    volumes:
      - ./:/app/
    depends_on:
      - cli
  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
    links:
      - fpm
