version: '3'
services:
  cli:
    build:
      context: ./cli
    image: phpenv/cli:latest
    links:
      - mysql
      - redis
      - beanstalkd
  composer:
    build:
      context: ./composer
      args:
        - COMPOSER_VERSION=${COMPOSER_VERSION}
    depends_on:
      - cli
    image: phpenv/composer:latest
  fpm:
    build:
      context: ./fpm
    expose:
      - 9000
    volumes:
      - ./:/app/
    depends_on:
      - cli
    links:
      - mysql
      - redis
      - beanstalkd
  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
    links:
      - fpm
  mysql:
    restart: always
    build:
      context: ./mysql
    ports:
      - 33061:3306
    volumes:
      - ./data/mysql/:/app/
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  redis:
    image: redis:alpine
    volumes:
      - ./data/redis/:/data
  beanstalkd:
    build:
      context: ./beanstalkd
    volumes:
      - ./data/beanstalkd/:/data
  node:
    image: node:6-alpine
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./:/usr/src/app
    expose:
      - 8080
